### PR TITLE
Only remove pure/view/constant from functions

### LINKED ISSUE #153: Instrumentation appears to be breaking constants
I have a library as follows

    pragma solidity ^0.4.18;

    import 'zeppelin-solidity/contracts/token/ERC20.sol';

    library KeyUtils {
        address constant private KEY_ADDRESS = 0x0;

        function getKEY() internal pure returns (ERC20) {
            return ERC20(KEY_ADDRESS);
        }
    }

and normal tests of this run fine.

But when I run with `solidity-coverage` I get this error

    /Users/davesag/src/myawesomeproject/coverageEnv/contracts/utils/KeyUtils.sol:13:5: TypeError: Library cannot have non-constant state variables
        address private KEY_ADDRESS = 0x0;
        ^-------------------------------^
    Compilation failed. See above.

Somehow the instrumentation process appears to have removed the `constant` keyword.

### PR DESCRIPTION
**Pull request by area**
Uses the preprocessor walking over the AST rather than a regex.

~Not mergeable -~ I want to do a test to show that this fixes #153, but wanted to see if this broke anything else in the tests, to begin with.

### CODE REVIEW

**Comment by area** [comment]
Added to the inheritance test to test this functionality. Puts the library in `assets` to demonstrate that it works even in the edge case brought up in #131.

**Comment by cgewecke** [comment]
Oh this is really good - I like that library fixture. Do you want to merge and publish? I am away from office till later today. Otherwise will wait until you are ready b/c do not merge warning in opening note.

**Comment by area** [comment]
This is now mergeable from my perspective. I can't publish right now either though!

**Comment by cgewecke** [comment]
Ok great, thanks!

**Pull request merged**
