### PR TITLE
[WIP] Support solidity 0.5.x + truffle v5 + web3.js 1.0.0-beta.x

### PR DESCRIPTION
**Pull request by obernardovieira**
Hi,

this is an important update for me and I believe is important for the community too.
The changes are very simple, in the first commit I just updated dependencies, since there was a lot of vulnerabilities, according to `npm audit`. In the second commit, I fixed the errors in order to make the coverage work again. Those changes are mostly related to *web3.js* package.

PS. **Do not** merge just yet, I still need to fix the tests.

### CODE REVIEW

**Comment by hiddentao** [comment]
What's the status of this?

**Comment by ukstv** [comment]
Just in case, LeapDAO maintains a fork that supports solidity 0.5.x and truffle v5: https://github.com/leapdao/solidity-coverage#master

**Comment by area** [comment]
I can confirm that the leapdao fork works. I've actually been working today on updating the tests over here based on the leapdao fork. #318 is the result, and there is a beta published with solidity 0.5.x support - please give it a go and let me know how it goes!

Closing in favour of #318, but I have taken some improvements here and incorporated them too, so thanks for the PR!

**Comment by obernardovieira** [comment]
Hi @area 
sure, will be a pleasure. Actually, I've been using my fork in a project for a while. I wanted to update the tests as well but didn't have time. I'm very happy to help with this.
Thank you so much. :tada:

**Pull request closed without merging**
