### PR TITLE
Add warnings for deprecated shell commands

### PR DESCRIPTION
**Pull request by cgewecke**
Ex:

```
$ testrpc-sc
```

Screen Shot 2019-09-18 at 9 07 46 PM

```
$ solidity-coverage
```
Screen Shot 2019-09-18 at 9 08 19 PM

### CODE REVIEW

**Comment by yxliang01** [comment]
@cgewecke Want to add https to the URL? :)

**Comment by cgewecke** [comment]
@yxliang01 When I copy paste the unprefixed url into the browser it resolves automatically. And looks cleaner/simpler to me, idk. 

Open to persuasion though.

**Comment by yxliang01** [comment]
@cgewecke What if in different browser or directly clicking on the link? Under that case, I believe it depends on the default protocol of the related software (potentially, terminal emulator + browser). So far, for the links I normally see in CLI, I would see them prefixed with `https://` , but not a big issue also I guess.

**Comment by cgewecke** [comment]
@yxliang01 Yes you're right about this - no one else omits the protocol. Will fix.

**Pull request merged**
