### PR TITLE
Bump parser to 0.7.0

### PR DESCRIPTION
**Pull request by junderw**
This will fix all issues with solidity 0.7.0 crashing on start.

### CODE REVIEW

**Comment by junderw** [comment]
... not sure why netlify is failing....

**Comment by junderw** [comment]
fixes #528

**Comment by junderw** [comment]
This is currently broken for 0.7.0 projects. A quick patch would be appreciated. Thanks! @area @cgewecke 

In the meantime I have published a temporary package with this dep bump added:

It can be installed as such:

```
npm install solidity-coverage@npm:junderw-solidity-coverage@0.7.10
```

Since `solidity-coverage` requires itself to be named solidity-coverage, the above install command will install my temp package as if it were `solidity-coverage`.

Anywho, this is just a temp solution for people looking to bump solidity version to 0.7.0 but need coverage, I will not maintain it moving forward, and once a patch is published here no one should use it anymore.

**Comment by area** [comment]
Hey - thanks for this PR. It's actually been a long time since I did a release (I think the last one I did still had our custom version of `ganache` tied to it...) and I'm not sure why `netlify` is failing either. I have cut and released a `beta` release from this branch though (`0.7.10-beta.0`) which at least gets us closer to where we want to be!

**Comment by junderw** [comment]
Thanks, I've updated my comment to use your patch.

**Pull request merged**
