### PR TITLE
Add Buidler plugin / Finalize API

### PR DESCRIPTION
**Pull request by cgewecke**
Continuation of #372. This is the root PR for phase II of the 0.7.x improvements. 

### Overview
+ Create [buidler][1] coverage plugin
+ Adapt integration test suite for buidler
+ Make plugin helpers/utilities +/- platform neutral.
+ E2E test vs [MolochVentures/moloch][2] (possibly others?)
+ Write Buidler and API documentation

### Tasks

⚠️ **Actively edited** ⚠️  

- [x] Plugin (#426)
    - [x] [in-flight instrumentation][3] 
      + (does not include feature proposed in #375)
    - [x] errors (#428)
    - [x] cli options (#435)
    - [x] [buidler 339][4] (Opted for `"main": "plugins/buidler.plugin.js"`) (#438)
- [x] Update integration test fixtures
- [x] Integration tests
    - [x] Standard (#426)
    - [x] Flags (#435)
    - [x] Errors (#428)
- [x] E2E
    - [x] sc-forks/buidler-e2e (#438)
    - [x] Moloch (#439)  
- [x] Documentation
    - [x] Buidler (#440)
    - [x] API (#447)
- [ ] Distribution
   - [ ] Moloch 
       + Looks like this will take some co-ordinating because there are changes pushed to master which break the tests & no CI. 

[1]: https://buidler.dev/
[2]: https://github.com/MolochVentures/moloch
[3]: https://github.com/sc-forks/solidity-coverage/pull/375#issuecomment-529708489
[4]: https://github.com/nomiclabs/buidler/issues/339

### CODE REVIEW

**Comment by roderik** [comment]
I was trying this plugin for buidler and we are using both the typescript stuff, and I need to pass a ganache setting. There is currently no d.ts file to extend the BuidlerConfig class.

**Comment by cgewecke** [comment]
@roderik Hi. 

Could you elaborate on this problem a bit - you're configuring .solcover.js providerOptions and seeing a TS error?

**Comment by roderik** [comment]
If you look at all the plugins, they all have a Typescript section in the docs: https://buidler.dev/plugins/nomiclabs-buidler-ethers.html#typescript-support

This makes it so that you can add plugin fields to the BuidlerConfig

```
const config: BuidlerConfig = {
  defaultNetwork: 'buidlerevm',
  solc: solcconfig,
  typechain: {
    target: 'ethers'
  },
  networks: {
    buidlerevm: {
      accounts: waffleDefaultAccounts.map(acc => ({
        balance: acc.balance,
        privateKey: acc.secretKey
      }))
    }
  },
  analytics: {
    enabled: false
  }
};
```

Without these, i cannot add the solidity-coverage configuration to the config. (for some reason configuring it via a separate config file did not pass my testrpc options)

**Comment by cgewecke** [comment]
@roderik Ah, this plugin is not designed the same way - it loads the options itself from `.solcover.js` only. 

> for some reason configuring it via a separate config file did not pass my testrpc options

That's a serious problem - if you share the ganache config I will try to reproduce and fix.

**Comment by cgewecke** [comment]
@roderik 

There's also a working 'complex project' example at [sc-forks/moloch][1] that might be helpful for comparison purposes.... 

Their buidler config defines a coverage network:
```javascript
coverage: {
   url: 'http://localhost:8555'
}
```

Their .solcover.js includes provider settings like `mnemonic`
```javascript
module.exports = {
  client: require('ganache-cli'),
  providerOptions: {
    mnemonic: "fetch local valve black attend double eye excite planet primary install allow"
  },
  skipFiles: [
    'Migrations.sol',
    'Token.sol',
    'oz',
    'gnosis-safe'
  ]
}
```

And lastly, the command is launched:
```
npx buidler coverage --network coverage
```



[1]: https://github.com/sc-forks/moloch

**Comment by cgewecke** [comment]
@roderik If you need any help or even if you get this working, please just lmk 

You're one of the first users and an experienced veteran - it would be great if you told me everything that's wrong with it :)

**Comment by roderik** [comment]
Will retry today, it has something to do with Waffle / buidlerevm / test-rpc

I put the waffle addresses into buidlerem like this

```
    buidlerevm: {
      accounts: waffleDefaultAccounts.map(acc => ({
        balance: acc.balance,
        privateKey: acc.secretKey
      }))
    }
```

and that works perfectly. When I switch to coverage, test-rpc starts with different addresses, and they have no ETH. So I tried to set the gasprice at 0 via the .solcover.js file, but that did not stick.

Then i was reading the code and i had the impression (could have misread) that putting a solcoverjs key in the builder config would also be picked up as config. There i have the accounts as well and i was thinking to push the addresses into test-rpc. 

But then there was no typescript definition so all hell broke loose :)

Will start again and try to make it work. Will share the result

**Comment by cgewecke** [comment]
Ah @roderik ganache is currently a requirement because of the way the coverage tool collects data - it launches a server instance and listens to its EVM. You just need to `require` it to the solcoverjs `client` option. 

Am talking to  NomicLabs about how to integrate BuidlerEVM - it's new. Looks amazing actually. 

I think you can do something very similar to the Moloch config in the comment above, but adapt the private key / balance array to the format described in the [ganache-core options](https://github.com/trufflesuite/ganache-core#options).

**Pull request merged**
