### PR TITLE
fixed parse error

### PR DESCRIPTION
**Pull request by leekt216**
it fixes issue with parse error of named return value
it was suppose to be array, but treated wrong

### CODE REVIEW

**Comment by cgewecke** [comment]
Hi @leekt216 

This branch isn't under active development anymore. Is there a reason you need to use the 0.6.x series?

**Comment by leekt216** [comment]
I dont use truffle

**Comment by cgewecke** [comment]
@leekt216 Could you describe how you're using solidity-coverage? There's a new API in 0.7.x that might also work for you.

**Comment by leekt216** [comment]
```
#!/usr/bin/env bash

set -o errexit -o pipefail

# Executes cleanup function at script exit.
trap cleanup EXIT

cleanup() {
  # Delete the symlink created to the allFiredEvents file solidity-coverage creates
  rm -f allFiredEvents
}

log() {
  echo "$*" >&2
}

# The allFiredEvents file is created inside coverageEnv, but solidity-coverage
# expects it to be at the top level. We create a symlink to fix this
ln -s coverageEnv/allFiredEvents allFiredEvents

OZ_TEST_ENV_COVERAGE=true npx solidity-coverage || log "Test run failed"

if [ "$CI" = true ]; then
  curl -s https://codecov.io/bash | bash -s -- -C "$CIRCLE_SHA1"
fi
```

this is my script for running solidity coverage

**Comment by cgewecke** [comment]
@leekt216 Ah! But solidity-coverage 0.6.x runs truffle by default. For example:

https://github.com/sc-forks/solidity-coverage/blob/25fd077a27d7283956b8001e709ac0981b654122/lib/app.js#L253-L258

Do you have a public project on Github you're trying to run coverage with I could take a look at? It might be simple to install the new version.

**Comment by leekt216** [comment]
Hmm didn't knew that... it makes sense for me to migrate to truffle...
There aren't any public repository
I should just use truffle anyway :)
Thanks for the kind reply

**Comment by cgewecke** [comment]
Oh sure! Just let me know if you run into further difficulties.

**Comment by leekt216** [comment]
Ah! i found why i didn't used any truffle 
```
module.exports = {
    norpc: true,
    testCommand: 'npm test',
    compileCommand: 'npm run compile',
    skipFiles: [
        'Migrations.sol',
        'mocks'
    ]
}
```
this is my .solcover.js

**Comment by cgewecke** [comment]
@leekt216 Ok, but what is happening when `npm test` and `npm compile` are run?

**Comment by leekt216** [comment]
Actually, my test env is highly inspired by openzeppelin-contracts

so, my script is same as https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/scripts/compile.sh

**Comment by cgewecke** [comment]
@leekt216 Yes, that's a good example to follow :) 

There's a [discussion at oz-test-environment][1] about how to integrate solidity-coverage 0.7.x, but it's not resolved. There needs to be a script that joins the API pieces together....

If your project is not super-complicated you could make a solcover.js like this:
```js
module.exports = {
    skipFiles: [
        'Migrations.sol',
        'mocks'
    ]
}
```

Add truffle and have a truffle-config.js like this:
```js
module.exports = {
  plugins: ["solidity-coverage"]
}
```
And only run it for coverage because coverage is pretty slow anyway. Idk what else you have specified in terms of compiler settings or special provider settings, but all that can be put in the truffle config. 

[1]: https://github.com/OpenZeppelin/openzeppelin-test-environment/issues/21

**Pull request closed without merging**
