### PR TITLE
More informative TestRPC failure logging

### PR DESCRIPTION
**Pull request by cag**
I needed this to see this:

https://travis-ci.org/gnosis/gnosis-contracts/jobs/253611700

### CODE REVIEW

**Comment by cgewecke** [comment]
@cag  Thanks! What's happening though, is the solc dep broken somewhere? Are you getting things to pass locally? I wonder if npm test rather than coverage in Travis passes.

**Comment by cgewecke** [comment]
@cag  Also, I was thinking that it might be sound to separate npm test and coverage in CI - putting the coverage in an `afterscript` run, because frankly this tool is a little brittle. That way your tests would run green but maybe sometimes you wouldn't get the report. If you do that you could also set `sudo: required` in travis.yml to bump the container mem up to 7.5MB - running testrpc twice there tends to cap out.

**Comment by cag** [comment]
@cgewecke It's kinda mysterious. The levelup dependency is reported to be installed by Travis as a dependency of various Ethereum related libraries, which is why I find it strange that the subsequent run of TestRPC would error like that. Additionally, when I run the `coverage` script locally, it runs fine and passes.

I don't have a good explanation for why this is happening, but your suggestion may be a good way forward for now.

**Comment by cgewecke** [comment]
Weird. Oh well, probably figure it out eventually. Peace.

**Pull request merged**
